name: Build huggingface Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Auto Obfuscate hug"]
    types:
      - completed
    branches:
      - huggingface

jobs:
  build:
    # 您的 if 条件判断是正确的，予以保留
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: huggingface

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 关键步骤：将仓库所有者（您的用户名）转换为小写
      - name: Convert owner to lowercase
        id: string_ops
        run: echo "owner_lc=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 在这里使用转换后的小写用户名
          tags: ghcr.io/${{ steps.string_ops.outputs.owner_lc }}/hugg:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=http server
            org.opencontainers.image.licenses=MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
